Fix compiler error with libxml2 2.12 and clang
This commit fixes the following compiler error.

graphml.c:1613:39: error: incompatible function pointer types passing
'void (*)(void *, xmlErrorPtr)' (aka 'void (*)(void *, struct _xmlError *)') to
parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)')
 [-Wincompatible-function-pointer-types]
 1613 |     xmlSetStructuredErrorFunc(&state, &igraph_i_libxml_structured_error_handler);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libxml2/libxml/xmlerror.h:898:29: note: passing argument to parameter 'handler' here
  898 |                                  xmlStructuredErrorFunc handler);
      |                                                         ^

According to the libxml2 changelog, this is due to a change in version 2.12:
https://download.gnome.org/sources/libxml2/2.12/libxml2-2.12.0.news